### ISSUE TITLE
Plan/Apply changes even when there aren't any changes

### ISSUE THREAD

**Issue by azuretek** [wavefrontHQ/terraform-provider-wavefront#11]
When we run a plan or apply using this provider it always shows that there are changes.

I'm running into the following issues with the `wavefront_dashboard` resource:
* tags don't get updated unless the whole resource is destroyed and recreated
* if the order of parameter_details changes the resource looks "changed" even though it's not.

I can provide terraform output or configs if necessary but it's pretty easy to recreate these issues.

**Comment by azuretek** [comment]
I rolled out a fix in our fork, it seems to resolve the paramater_details issue.

https://github.com/getoutreach/terraform-provider-wavefront/commit/b77b1490dded41ce55dbdd6943a2a5bac6ae035d

I wasn't able to find a solution to the `tags` issue, it seems like a problem in the upstream wavefront-go client

**Comment by MikeMcMahon** [comment]
have a few other changes to wrap up that will result in another point release, but this has been fixed in master.
