### ISSUE TITLE
Terraform Provider Development Program - first review

### ISSUE THREAD

**Issue by cgriggs01** [wavefrontHQ/terraform-provider-wavefront#15]
I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the master branch at git commit `eead883`

- [x] A makefile should be added with the GNUmakefile which is standard across all Terraform providers, feel free to copy the [GitHub provider makefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=wavefront

- [x] Along with the makefile, there are a few scripts that are needed for testing and building the provider integration. You’ll need to add [changelog-links.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/changelog-links.sh) and [gogetcookie.sh](https://github.com/terraform-providers/terraform-provider-github/blob/master/scripts/gogetcookie.sh) to you scripts/ directory. 

- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run the unit tests on each PR that is opened. Can you please add a .travis.yaml file to with the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [x] We are now adding `.go-version` files to each terraform provider, and should be set to `1.14.3`.

- [x] You will need to build website documentation in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html) for each resource and data source, these are all written in markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example. 
-The Terraform.io website uses our terraform-website/ repository that is used as the middleman to sync all the terraform and provider documentation from all of their own repositories. To deploy the website locally follow the steps outlined in the README.
	- Once you've synced the current submodules there are 3 more steps required for adding you provider
	- Add the wavefont provider as a submodule to the terraform-website/ directory with: `git submodule add -b master https://github.com/wavefrontHQ/terraform-provider-wavefont ext/providers/wavefont`
	- Then you'll have to create two symbolic links to this module, first change to the working directory terraform-website/content/source/docs/providers/ the run: `ln -s ../../../../ext/providers/wavefont/website/docs wavefont`
	- And then change to the working directory to "terraform-website/content/source/layouts/" to run: `ln -s ../../../ext/providers/wavefont/website/wavefont.erb`
	- After those additions, you can then run the "make website" target to spin up the website using Docker desktop. 

- [x] The CHANGELOG formatting will have to be updated to conform to the standard provider format since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [x] One of our Terraform ecosystem engineers built a linter that helps align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] The acceptance tests should all run and pass with the make target `testacc`.  We run these tests every night from a TeamCity environment. 

Once all this item are address, there will be one more final review cycle and then we can move on to the migration and release of this provider. Let me know if you have any questions. 

Best,
Chris

**Comment by MikeMcMahon** [comment]
Getting started on the requested changes ASAP!

**Comment by MikeMcMahon** [comment]
@cgriggs01 the last two items left are travis integration for testing ( i wanted to ask about that, since the testing requires real credentials to a wavefront account, how do we want to go about securing that) and the last item is mostly just fixing some tests to align with API changes that happened on our end (next week).  Everything else on the checklist has been completed!

**Comment by MikeMcMahon** [comment]
@cgriggs01 what are our next steps, we have merged all of the required changes w/ master now.

**Comment by cgriggs01** [comment]
Hey Team, 

Thanks for the work you've put in on this provider. All my requirement have been met and I am ready to start the release process. 

This final phase of the partner provider program will go as follows:
- A repository under the same name `terraform-providers-wavefront` will be created in the  [github.com/terraform-repositories/](http://github.com/terraform-repositories/)  organization. 
- Your provider code will be pushed up to the new repository
- The binaries during release are pulled from the master branch. 
- A `stable-website` branch will be created, this is where the  [terraform.io](http://terraform.io/)  provider documentation is source from. During each release, a bot will commit the changes in your master branch to the stable-website branch. If you need to make changes to the provider website docs in between releases, you can cherry-pick the commits to the stable-website branch. 
- The first release will be tagged `2.3.0` per the CHANGELOG.md
- You and whomever else on your team will be granted “write” access over the new repository are you are still seen as the owners and maintainers of the provider. Can you send us the list on maintainers email addresses and GitHub usernames to terraform-provider-dev@hashicorp.com.
- Whomever is added as a maintainer to the provider repository will also be granted an account on our #committers-terraform Slack channel, where you will request new versioned releases of the provider. 

Excited to get this released with you guess.

**Comment by MikeMcMahon** [comment]
@cgriggs01 thank you again for your support on this; I have sent an email to the address requested.
