### ISSUE TITLE
wavefront_dashboard cannot update tags

### ISSUE THREAD

**Issue by lihaiswu** [wavefrontHQ/terraform-provider-wavefront#16]
tags in resource wavefront_dashboard can only be valid when creating it at the first time. After that, tags cannot be updated via resource wavefront_dashboard

1. successfully created wavefront_dashboard resource with tags = [ "a"] 
2. update tags = [ "a"]  to tags = [ "a", "b"]
3. run terraform again. The dashboard still only have tag "a".

**Comment by MikeMcMahon** [comment]
this has been addressed in master and a new release will be cut soon with this fix.
