### ISSUE TITLE
sparkline_decimal_precision not work for 0

### ISSUE THREAD

**Issue by lihaiswu** [wavefrontHQ/terraform-provider-wavefront#17]
wavefront_dashboard cannot apply sparkline_decimal_precision with 0 value. Must use greater than 0 to make the field work. It should support 0.

**Comment by MikeMcMahon** [comment]
Hey we've finally gotten into terraform proper, please feel free to file GH issues over at https://github.com/terraform-providers/terraform-provider-wavefront now!
