### ISSUE TITLE
Confusing error when leaving 'target:' out of alert target settings

### ISSUE THREAD

**Issue by jeffmace** [wavefrontHQ/terraform-provider-wavefront#18]
The provider will throw an error like `{"status":{"result":"ERROR","message":"Invalid notification specified: null","code":400}}` if you do not include `target:` in the target setting. The provider should either:

- Throw an error indicating that `target:` is required
- Prepend `target:` before submitting the value to Wavefront

**Comment by MikeMcMahon** [comment]
Added a new `target_id` attribute to alert targets as well as validation on `target` to ensure it is in the proper format.
