### ISSUE TITLE
Terraform Partner Provider Program

### ISSUE THREAD

**Issue by cgriggs01** [wavefrontHQ/terraform-provider-wavefront#2]
Hi Team,

Thanks for reaching out to submit this provider to the Terraform community provider, my name is Chris Griggs and I work at HashiCorp running [Partner Terraform Provider Development program](https://www.terraform.io/guides/terraform-provider-development-program.html)

Let me know if you'd be interesting in participating.

Best,
Chris

**Comment by MikeMcMahon** [comment]
Hey @cgriggs01 absolutely, we're in the process of relicensing to MPL as our intention is for HashiCorp/Vendor level of integration!

**Comment by MikeMcMahon** [comment]
@cgriggs01 we just wrapped up getting the project re-licensed to MPL-2.0 and want to begin the next steps towards participation. :)

**Comment by cgriggs01** [comment]
Hi Team,

Apologies for the delay, but I was able to complete the first review of your Terraform provider. I've opened a new issue https://github.com/wavefrontHQ/terraform-provider-wavefront/issues/15 with the first set of feedback. 

Closing this issue now.
