### ISSUE TITLE
Respect the HTTPS_PROXY environment variable

### ISSUE THREAD

**Issue by jgspratt** [wavefrontHQ/terraform-provider-wavefront#21]
I am trying to use this provider behind a proxy and it does not appear to respect the `HTTPS_PROXY` environment variable.

Can you look into this?

**Comment by MikeMcMahon** [comment]
fixed in latest rc! https://github.com/wavefrontHQ/terraform-provider-wavefront/releases/tag/v2.3.0-rc1
