### ISSUE TITLE
Support for singleStat chart type

### ISSUE THREAD

**Issue by ssgao** [wavefrontHQ/terraform-provider-wavefront#22]
Hi Wavefront support,

It seems like single stat chart type is defined in chartAttributes, which is currently missing in `wavefront_dashboard`.

Any plan on supporting it?

Thanks

**Comment by MikeMcMahon** [comment]
Hey we've finally gotten into terraform proper, please feel free to file GH issues over at https://github.com/terraform-providers/terraform-provider-wavefront now!

**Comment by ssgao** [comment]
thanks, opened https://github.com/terraform-providers/terraform-provider-wavefront/issues/1
