### ISSUE TITLE
Which Go API?

### ISSUE THREAD

**Issue by bgreg1012** [wavefrontHQ/terraform-provider-wavefront#9]
Hi, I was interested in making a PR for the addition of chartAttributes. In the [CONTRIBUTING.md](https://github.com/wavefrontHQ/terraform-provider-wavefront/blob/master/CONTRIBUTING.md) I see you use [go-wavefront](https://github.com/spaceapegames/go-wavefront) (I have a PR submitted there for my changes), but I just noticed that the terraform-provider-wavefront code specifies [go-wavefront-management-api](https://github.com/wavefrontHQ/go-wavefront-management-api). Should I be submitting my PR there instead? Thanks!

**Comment by rorski** [comment]
We could also use this! Not being able to set chart sizes is a major limiting factor in the dashboard resource.

**Comment by MikeMcMahon** [comment]
we are using the go-wavefront-management-api and I will cleanup the CONTRIBUTING.md docs. Kind regards.
